version: '3.9'

services:
  pkcs11-ssl-certificate:
    image: usmans/pkcs11-ssl-certs
    container_name: 'pkcs11-ssl-certs'
    build:
      context: ./initcerts
    volumes:
      - ./certs:/certs
  pkcs11-server-java11:
    image: usmans/pkcs11-server-softhsm
    container_name: 'pkcs11-server-softhsm'
    build:
      context: ./server
      dockerfile: ./SoftHsm.Dockerfile
    depends_on:
      pkcs11-ssl-certificate:
        condition: service_completed_successfully  
    ports:
      - 8443:8443
    volumes:
      - ./certs:/certs